ML-453 Adding synthesized logo and pic for data rebalancing
synthesized-io/synthesized-notebooks pull request #7
Opened 2021-07-12 15:10 UTC by akanksha1304

Added Synthesized logo and picture of data rebalancing (same as in SDK).

I will add the picture for privacy (same as in SDK) once there is a privacy section in the demo notebook.

2021-07-13 09:03 UTC, jamied157 requested changes
Looks good, could we start with a big logo at the top of the demo? I think the logos could be a bit bigger in general. Are there any more we can add or is that it?

2021-07-20 13:10 UTC, simonhkswan requested changes

2021-07-20 13:10 UTC, simonhkswan commented on synthesized-sdk.ipynb
> +   "version": "3.6.7"
Can we revert this change here?
```suggestion
   "version": "3.7.10"
```

2021-07-20 13:23 UTC, simonhkswan approved these changes

2021-07-20 13:25 UTC, merged